-- MySQL Script generated by MySQL Workbench
-- Tue Jul  9 18:56:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stocks` (
  `id` INT NOT NULL,
  `quantity` INT NULL,
  `status` INT NULL,
  `stock_min` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `code` VARCHAR(100) NULL,
  `url` VARCHAR(100) NULL,
  `price` FLOAT NULL,
  `brand` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `stocks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `stocks_id`),
  INDEX `fk_products_stocks1_idx` (`stocks_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_stocks1`
    FOREIGN KEY (`stocks_id`)
    REFERENCES `mydb`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicles` (
  `id` INT NOT NULL,
  `brand` VARCHAR(45) NULL,
  `license plate` INT NULL,
  `model` INT NULL,
  `year` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `address` TINYINT NULL,
  `address_number` TINYINT NULL,
  `address_floor` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` TINYINT NULL,
  `business_name` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `cuil/cuit` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `vehicles_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`, `vehicles_id`, `address_id`),
  INDEX `fk_clients_vehicles1_idx` (`vehicles_id` ASC) VISIBLE,
  INDEX `fk_clients_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_vehicles1`
    FOREIGN KEY (`vehicles_id`)
    REFERENCES `mydb`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clients_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suppliers` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` TINYINT NULL,
  `business_name` VARCHAR(100) NULL,
  `cuil/cuit` VARCHAR(100) NULL,
  `status` FLOAT NULL,
  `dni` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`, `address_id`),
  INDEX `fk_suppliers_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_suppliers_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movements` (
  `id` INT NOT NULL,
  `type` ENUM('venta', 'compra', 'retiro') NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoices` (
  `id` INT NOT NULL,
  `invoice_number` INT NULL,
  `issue_date` INT NULL,
  `total_amount` INT NULL,
  `sender_date` VARCHAR(45) NULL,
  `due_date` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `id` INT NOT NULL,
  `quantity` FLOAT NULL,
  `price_unit` FLOAT NULL,
  `total` FLOAT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `clients_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `movements_id` INT NOT NULL,
  `invoices_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clients_id`, `products_id`, `movements_id`, `invoices_id`),
  INDEX `fk_sales_clients_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_sales_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_sales_movements1_idx` (`movements_id` ASC) VISIBLE,
  INDEX `fk_sales_invoices1_idx` (`invoices_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_clients`
    FOREIGN KEY (`clients_id`)
    REFERENCES `mydb`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_movements1`
    FOREIGN KEY (`movements_id`)
    REFERENCES `mydb`.`movements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_invoices1`
    FOREIGN KEY (`invoices_id`)
    REFERENCES `mydb`.`invoices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `id` INT NOT NULL,
  `quantity` FLOAT NULL,
  `price_unit` FLOAT NULL,
  `total` FLOAT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `suppliers_id` INT NOT NULL,
  `movements_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `products_stocks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `suppliers_id`, `movements_id`, `products_id`, `products_stocks_id`),
  INDEX `fk_purchase_suppliers1_idx` (`suppliers_id` ASC) VISIBLE,
  INDEX `fk_purchase_movements1_idx` (`movements_id` ASC) VISIBLE,
  INDEX `fk_purchase_products1_idx` (`products_id` ASC, `products_stocks_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_suppliers1`
    FOREIGN KEY (`suppliers_id`)
    REFERENCES `mydb`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_movements1`
    FOREIGN KEY (`movements_id`)
    REFERENCES `mydb`.`movements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_products1`
    FOREIGN KEY (`products_id` , `products_stocks_id`)
    REFERENCES `mydb`.`products` (`id` , `stocks_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` INT NOT NULL,
  `first_name` INT NULL,
  `last_name` INT NULL,
  `dni` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attributes` (
  `id` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  `name` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `name` INT NULL,
  `description` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `attributes_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`, `attributes_id`, `products_id`),
  INDEX `fk_categories_attributes1_idx` (`attributes_id` ASC) VISIBLE,
  INDEX `fk_categories_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_attributes1`
    FOREIGN KEY (`attributes_id`)
    REFERENCES `mydb`.`attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`attribute_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`attribute_types` (
  `id` INT NOT NULL,
  `name` INT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `attributes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `attributes_id`),
  INDEX `fk_attribute_types_attributes1_idx` (`attributes_id` ASC) VISIBLE,
  CONSTRAINT `fk_attribute_types_attributes1`
    FOREIGN KEY (`attributes_id`)
    REFERENCES `mydb`.`attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` TINYINT NULL,
  `status` TINYINT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service_order` (
  `id` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  `status` TINYINT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `sales_id` INT NOT NULL,
  `sales_clients_id` INT NOT NULL,
  `sales_products_id` INT NOT NULL,
  `sales_movements_id` INT NOT NULL,
  `employees_id` INT NOT NULL,
  `vehicles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sales_id`, `sales_clients_id`, `sales_products_id`, `sales_movements_id`, `employees_id`, `vehicles_id`),
  INDEX `fk_service_order_sales1_idx` (`sales_id` ASC, `sales_clients_id` ASC, `sales_products_id` ASC, `sales_movements_id` ASC) VISIBLE,
  INDEX `fk_service_order_employees1_idx` (`employees_id` ASC) VISIBLE,
  INDEX `fk_service_order_vehicles1_idx` (`vehicles_id` ASC) VISIBLE,
  CONSTRAINT `fk_service_order_sales1`
    FOREIGN KEY (`sales_id` , `sales_clients_id` , `sales_products_id` , `sales_movements_id`)
    REFERENCES `mydb`.`sales` (`id` , `clients_id` , `products_id` , `movements_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `mydb`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_order_vehicles1`
    FOREIGN KEY (`vehicles_id`)
    REFERENCES `mydb`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bank_checks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bank_checks` (
  `id` INT NOT NULL,
  `sender` INT NULL,
  `date_recipient_bank` INT NULL,
  `bank_name` INT NULL,
  `date_delivered_bank_check` VARCHAR(45) NULL,
  `check_number` VARCHAR(45) NULL,
  `collection_date` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `date_delivered_bank_check` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payments` (
  `id` INT NOT NULL,
  `payment_date` FLOAT NULL,
  `payment_method` FLOAT NULL,
  `description` FLOAT NULL,
  `amount` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `invoices_id` INT NOT NULL,
  `bank_checks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `invoices_id`, `bank_checks_id`),
  INDEX `fk_payments_invoices1_idx` (`invoices_id` ASC) VISIBLE,
  INDEX `fk_payments_bank_checks1_idx` (`bank_checks_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_invoices1`
    FOREIGN KEY (`invoices_id`)
    REFERENCES `mydb`.`invoices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_bank_checks1`
    FOREIGN KEY (`bank_checks_id`)
    REFERENCES `mydb`.`bank_checks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cash_flows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cash_flows` (
  `id` INT NOT NULL,
  `type` INT NULL,
  `transaction_type` INT NULL,
  `date` INT NULL,
  `payment_method` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  `movements_id` INT NOT NULL,
  `payments_id` INT NOT NULL,
  PRIMARY KEY (`id`, `movements_id`, `payments_id`),
  INDEX `fk_cash_flows_movements1_idx` (`movements_id` ASC) VISIBLE,
  INDEX `fk_cash_flows_payments1_idx` (`payments_id` ASC) VISIBLE,
  CONSTRAINT `fk_cash_flows_movements1`
    FOREIGN KEY (`movements_id`)
    REFERENCES `mydb`.`movements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cash_flows_payments1`
    FOREIGN KEY (`payments_id`)
    REFERENCES `mydb`.`payments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
